### ISSUE TITLE
Programming with PICKIT2 successful 

### ISSUE THREAD

**Issue by ibarrajo** [tinfever/FU-Dyson-BMS#25]
Just as a note for people who have a PICKIT2 and not the PICKIT3.

PICKIT2 does not support PIC16LF1847 and will refuse to communicate with it.

Nonetheless, I was able to flash this firmware successfully by updating my `PK2DeviceFile.dat` in `C:\Program Files (x86)\Microchip\PICkit 2 v2` with the device file provided in the software for PICKIT3.

`PIC16LF1847` is detected and works

![image](https://user-images.githubusercontent.com/1480657/223285729-1e59f1a4-f7ea-4816-8ed1-9460c4febd37.png)

**Comment by liujixu1984** [comment]
Hello, I have a Pickit2 and Dyson V6 battery. Can you please send me an explanation of your successful use of Pickit2 to flash the device? thank you.

**Comment by ibarrajo** [comment]
I'm going to close the issue, since I just intended to communicate my findings. 

To be clear, I just updated my `PK2DeviceFile.dat` used by PICkit2 by replacing it with the same file that comes with Microchip's PICkit3 Programmer Application. I did this because I didn't want to buy a PICkit3 when I just had a PICkit2 already.
